import { useQuery, useMutation } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Loader2, Sparkles, Star, RefreshCw, FileText } from "lucide-react";
import { toast } from "sonner";
import { generateLandingCopy, getLandingCopy } from "@/lib/landing-copy.functions";

export function LandingCopyPreview({
  productId,
  productTitle,
}: {
  productId: string;
  productTitle?: string;
}) {
  const getFn = useServerFn(getLandingCopy);
  const genFn = useServerFn(generateLandingCopy);

  const q = useQuery({
    queryKey: ["landing-copy", productId],
    queryFn: () => getFn({ data: { productId } }),
  });

  const gen = useMutation({
    mutationFn: (force: boolean) => genFn({ data: { productId, force } }),
    onSuccess: () => {
      toast.success("Landing copy generated");
      q.refetch();
    },
    onError: (e: any) => toast.error(e?.message || "Generation failed"),
  });

  if (q.isLoading) {
    return <div className="py-10 text-center text-sm text-muted-foreground">Loading copy…</div>;
  }

  const row = q.data as any;

  if (!row) {
    return (
      <Card className="border-dashed border-border/60">
        <CardContent className="p-8 text-center space-y-3">
          <FileText className="w-10 h-10 mx-auto text-muted-foreground" />
          <p className="text-sm text-muted-foreground">
            No AI landing copy generated yet for this product.
          </p>
          <Button onClick={() => gen.mutate(false)} disabled={gen.isPending}>
            {gen.isPending ? (
              <Loader2 className="w-4 h-4 mr-1 animate-spin" />
            ) : (
              <Sparkles className="w-4 h-4 mr-1" />
            )}
            Generate Landing Copy
          </Button>
        </CardContent>
      </Card>
    );
  }

  const painPoints = (row.pain_points || []) as Array<{ title: string; body: string }>;
  const faqs = (row.faqs || []) as Array<{ question: string; answer: string }>;
  const reviews = (row.reviews || []) as Array<{
    name: string;
    rating: number;
    title: string;
    body: string;
    verified?: boolean;
  }>;

  const copyMarkdown = () => {
    const md = [
      `# ${row.headline}`,
      `> ${row.subheadline}`,
      "",
      "## Pain Points",
      ...painPoints.map((p) => `- **${p.title}** — ${p.body}`),
      "",
      "## FAQs",
      ...faqs.map((f) => `**${f.question}**\n${f.answer}`),
      "",
      "## Reviews",
      ...reviews.map((r) => `⭐ ${r.rating}/5 — ${r.title} — ${r.name}\n${r.body}`),
    ].join("\n");
    navigator.clipboard.writeText(md).then(() => toast.success("Copied as Markdown"));
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2 justify-between">
        <div className="text-[11px] text-muted-foreground">
          Generated by <span className="font-mono">{row.generated_by || "AI"}</span> · last updated{" "}
          {new Date(row.updated_at).toLocaleString()}
        </div>
        <div className="flex gap-2">
          <Button size="sm" variant="outline" onClick={copyMarkdown}>
            Copy as Markdown
          </Button>
          <Button size="sm" onClick={() => gen.mutate(true)} disabled={gen.isPending}>
            {gen.isPending ? (
              <Loader2 className="w-3.5 h-3.5 mr-1 animate-spin" />
            ) : (
              <RefreshCw className="w-3.5 h-3.5 mr-1" />
            )}
            Regenerate
          </Button>
        </div>
      </div>

      {/* Hero */}
      <Card className="border-border/50 overflow-hidden">
        <CardContent className="p-6 bg-gradient-to-br from-primary/10 via-transparent to-pink-500/10 text-center space-y-3">
          <h2 className="text-2xl md:text-3xl font-bold leading-tight bg-gradient-to-r from-primary to-pink-600 bg-clip-text text-transparent">
            {row.headline}
          </h2>
          <p className="text-sm md:text-base text-muted-foreground max-w-xl mx-auto">
            {row.subheadline}
          </p>
          <Button size="lg" className="mt-2" disabled>
            Shop {productTitle ? productTitle.split(" ").slice(0, 3).join(" ") : "Now"}
          </Button>
        </CardContent>
      </Card>

      {/* Pain Points */}
      {painPoints.length > 0 && (
        <div>
          <h3 className="font-semibold text-sm mb-2">Pain Points Solved</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            {painPoints.map((p, i) => (
              <Card key={i} className="border-border/50">
                <CardContent className="p-4 space-y-1.5">
                  <div className="w-7 h-7 rounded-full bg-primary/10 flex items-center justify-center text-primary font-bold text-sm">
                    {i + 1}
                  </div>
                  <p className="font-semibold text-sm">{p.title}</p>
                  <p className="text-xs text-muted-foreground leading-relaxed">{p.body}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      )}

      {/* FAQs */}
      {faqs.length > 0 && (
        <div>
          <h3 className="font-semibold text-sm mb-2">FAQ</h3>
          <Card className="border-border/50">
            <CardContent className="p-2">
              <Accordion type="single" collapsible className="w-full">
                {faqs.map((f, i) => (
                  <AccordionItem key={i} value={`q${i}`}>
                    <AccordionTrigger className="text-sm">{f.question}</AccordionTrigger>
                    <AccordionContent className="text-xs text-muted-foreground">
                      {f.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Reviews */}
      {reviews.length > 0 && (
        <div>
          <h3 className="font-semibold text-sm mb-2">Customer Reviews</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {reviews.map((r, i) => (
              <Card key={i} className="border-border/50">
                <CardContent className="p-4 space-y-2">
                  <div className="flex items-center gap-2">
                    <div className="w-8 h-8 rounded-full bg-primary/15 text-primary flex items-center justify-center font-bold text-xs">
                      {r.name
                        ?.split(" ")
                        .map((x) => x[0])
                        .join("")
                        .slice(0, 2)
                        .toUpperCase()}
                    </div>
                    <div className="flex-1">
                      <p className="text-xs font-semibold">{r.name}</p>
                      <div className="flex items-center gap-0.5">
                        {Array.from({ length: 5 }).map((_, j) => (
                          <Star
                            key={j}
                            className={`w-3 h-3 ${j < r.rating ? "fill-amber-400 text-amber-400" : "text-muted-foreground/30"}`}
                          />
                        ))}
                      </div>
                    </div>
                    {r.verified && (
                      <Badge
                        variant="outline"
                        className="text-[9px] bg-emerald-500/10 text-emerald-700 border-emerald-500/30"
                      >
                        Verified
                      </Badge>
                    )}
                  </div>
                  <p className="text-xs font-medium">{r.title}</p>
                  <p className="text-xs text-muted-foreground leading-relaxed">{r.body}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
