// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://vwnxnpgujxtomkxdxuvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3bnhucGd1anh0b21reGR4dXZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxODMzMDUsImV4cCI6MjA4Nzc1OTMwNX0.xGv7eZudP8Gm9N1tkzSCqJydygTT-t2ZjJh_BCcJ2Lo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    ...(typeof window !== "undefined" ? { storage: localStorage } : {}),
    persistSession: typeof window !== "undefined",
    autoRefreshToken: true,
  },
});
